version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://user:test@db:5432/mydb?schema=public
      - JWT_SECRET=mysecretkey
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: test
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
